defaults: &defaults
  :cache: true
  :admin:
    :user: admin
    :password: password
  :database:
    :adapter: sqlite3
    :database: db/parkingday.db

:development:
  <<: *defaults
  
:test:
  <<: *defaults
  :database:
    :adapter: sqlite3
    :database: db/parkingday_test.db